apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.21.0
appVersion: 0.2.9
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
